from fpdf import FPDF
import os
 
class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Research Report - Advanced RAG System', 0, 1, 'C')
        self.ln(5)
        self.set_font('Arial', '', 10)
        self.set_text_color(128, 128, 128)  # Gray color
        self.cell(0, 5, 'Intelligent Research Paper Analysis & Question Answering', 0, 1, 'C')
        self.ln(5)
        self.set_draw_color(0, 0, 0)
        self.line(10, 35, 200, 35)  # Add a line separator
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)  # Gray color
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def create_pdf_report(content: str, filename="research_report.pdf"):
    """
    Generates a professional PDF from the text content using FPDF.
    """
    pdf = PDFReport()
    pdf.add_page()
    
    # Set up the main content area
    pdf.set_font("Arial", size=12)
    pdf.set_text_color(0, 0, 0)  # Black color for content
    
    # Handle encoding issues
    safe_content = content.replace("’", "'").replace("“", '"').replace("”", '"').replace("–", "-")
    
    # Split content into lines to handle long text properly
    lines = safe_content.split('\n')
    for line in lines:
        # Make sure the line fits in the page width
        if len(line) > 0:
            # Use multi_cell to handle text wrapping with better formatting
            pdf.multi_cell(0, 8, line[:180], ln=True, align='L')  # Limit line width to fit page
        else:
            pdf.ln(4)  # Add some space for empty lines
    
    # Add a professional footer note
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 9)
    pdf.set_text_color(128, 128, 128)  # Gray color
    pdf.cell(0, 5, 'Generated by Advanced RAG Academic Assistant', 0, 1, 'C')
    
    pdf.output(filename)
